2016/01/18 12:16:48 Info > Staring data upload process
2016/01/18 12:17:31 Info > Completed data upload process.0 netflows.210 performancecounters. = Total Elapsed Time: 00:00:42.2510000
2016/01/18 12:20:22 Info > Starting workload performance collection
2016/01/18 12:22:59 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 12:23:17 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 12:23:49 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 12:24:08 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 12:24:34 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 12:24:49 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 12:25:25 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 12:25:41 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 12:26:12 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 12:26:12 Info > Completed performance collection | Elapsed Time 00:05:49.9420000 
2016/01/18 12:34:35 Info > Staring platform inventory process
2016/01/18 12:34:36 Info > Started data mirroring process for Dimension Data : NA9
2016/01/18 12:34:45 Info > Completed data mirroring process for Dimension Data : NA9.0 new workloads.0 updated platform networks.4 updated workloads.0 removed workloads. = Total Execute Time: 00:00:09.6400000
2016/01/18 12:34:45 Info > Completed data mirroring process.0 new platforms, 1 updated platforms = total elapsed time: 00:00:09.8700000
2016/01/18 12:56:12 Info > Starting workload performance collection
2016/01/18 12:58:53 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 12:59:11 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 12:59:45 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 12:59:59 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 01:00:35 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 01:00:53 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 01:01:23 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 01:01:40 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 01:02:14 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 01:02:14 Info > Completed performance collection | Elapsed Time 00:06:02.3800000 
2016/01/18 01:17:31 Info > Staring data upload process
2016/01/18 01:18:51 Info > Completed data upload process.0 netflows.420 performancecounters. = Total Elapsed Time: 00:01:20.2610000
2016/01/18 01:32:14 Info > Starting workload performance collection
2016/01/18 01:34:45 Info > Staring platform inventory process
2016/01/18 01:34:45 Info > Started data mirroring process for Dimension Data : NA9
2016/01/18 01:34:55 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 01:34:58 Info > Completed data mirroring process for Dimension Data : NA9.0 new workloads.0 updated platform networks.4 updated workloads.0 removed workloads. = Total Execute Time: 00:00:12.9320000
2016/01/18 01:34:58 Info > Completed data mirroring process.0 new platforms, 1 updated platforms = total elapsed time: 00:00:13.1220000
2016/01/18 01:35:15 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 01:35:47 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 01:36:02 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 01:36:38 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 01:36:55 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 01:37:27 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 01:37:42 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 01:38:13 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 01:38:13 Info > Completed performance collection | Elapsed Time 00:05:59.2210000 
2016/01/18 02:08:13 Info > Starting workload performance collection
2016/01/18 02:10:56 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 02:11:12 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 02:11:45 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 02:12:01 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 02:12:37 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 02:12:54 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 02:13:27 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 02:13:43 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 02:14:16 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 02:14:16 Info > Completed performance collection | Elapsed Time 00:06:02.2350000 
2016/01/18 02:18:51 Info > Staring data upload process
2016/01/18 02:20:12 Info > Completed data upload process.0 netflows.420 performancecounters. = Total Elapsed Time: 00:01:21.1870000
2016/01/18 02:34:58 Info > Staring platform inventory process
2016/01/18 02:34:59 Info > Started data mirroring process for Dimension Data : NA9
2016/01/18 02:35:08 Info > Completed data mirroring process for Dimension Data : NA9.0 new workloads.0 updated platform networks.4 updated workloads.0 removed workloads. = Total Execute Time: 00:00:09.5770000
2016/01/18 02:35:08 Info > Completed data mirroring process.0 new platforms, 1 updated platforms = total elapsed time: 00:00:09.8050000
2016/01/18 02:44:16 Info > Starting workload performance collection
2016/01/18 02:47:17 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 02:47:32 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 02:48:07 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 02:48:22 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 02:48:59 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 02:49:16 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 02:49:46 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 02:50:00 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 02:50:30 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 02:50:30 Info > Completed performance collection | Elapsed Time 00:06:14.7190000 
2016/01/18 03:20:12 Info > Staring data upload process
2016/01/18 03:20:30 Info > Starting workload performance collection
2016/01/18 03:21:01 Info > Completed data upload process.0 netflows.210 performancecounters. = Total Elapsed Time: 00:00:48.2580000
2016/01/18 03:23:26 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 03:23:42 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 03:24:13 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 03:24:30 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 03:25:03 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 03:25:19 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 03:25:55 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 03:26:13 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 03:26:45 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 03:26:45 Info > Completed performance collection | Elapsed Time 00:06:15.0410000 
2016/01/18 03:35:08 Info > Staring platform inventory process
2016/01/18 03:35:08 Info > Started data mirroring process for Dimension Data : NA9
2016/01/18 03:35:18 Info > Completed data mirroring process for Dimension Data : NA9.0 new workloads.0 updated platform networks.4 updated workloads.0 removed workloads. = Total Execute Time: 00:00:09.6850000
2016/01/18 03:35:18 Info > Completed data mirroring process.0 new platforms, 1 updated platforms = total elapsed time: 00:00:09.9440000
2016/01/18 03:56:45 Info > Starting workload performance collection
2016/01/18 03:59:30 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 03:59:47 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 04:00:20 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 04:00:38 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 04:01:14 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 04:01:30 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 04:02:04 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 04:02:21 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 04:02:56 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 04:02:56 Info > Completed performance collection | Elapsed Time 00:06:10.3280000 
2016/01/18 04:21:01 Info > Staring data upload process
2016/01/18 04:22:27 Info > Completed data upload process.0 netflows.420 performancecounters. = Total Elapsed Time: 00:01:26.4560000
2016/01/18 04:32:56 Info > Starting workload performance collection
2016/01/18 04:35:18 Info > Staring platform inventory process
2016/01/18 04:35:19 Info > Started data mirroring process for Dimension Data : NA9
2016/01/18 04:35:29 Info > Completed data mirroring process for Dimension Data : NA9.0 new workloads.0 updated platform networks.4 updated workloads.0 removed workloads. = Total Execute Time: 00:00:10.7970000
2016/01/18 04:35:29 Info > Completed data mirroring process.0 new platforms, 1 updated platforms = total elapsed time: 00:00:11.2520000
2016/01/18 04:35:46 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 04:36:01 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 04:36:21 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 04:36:54 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 04:37:12 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 04:37:45 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 04:38:01 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 04:38:34 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 04:38:52 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 04:38:52 Info > Completed performance collection | Elapsed Time 00:05:56.2630000 
2016/01/18 05:08:52 Info > Starting workload performance collection
2016/01/18 05:11:50 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 05:12:05 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 05:12:23 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 05:12:55 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 05:13:10 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 05:13:27 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 05:14:02 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 05:14:18 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 05:14:57 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 05:14:57 Info > Completed performance collection | Elapsed Time 00:06:05.3110000 
2016/01/18 05:22:27 Info > Staring data upload process
2016/01/18 05:23:58 Info > Completed data upload process.0 netflows.420 performancecounters. = Total Elapsed Time: 00:01:30.7280000
2016/01/18 05:35:29 Info > Staring platform inventory process
2016/01/18 05:35:30 Info > Started data mirroring process for Dimension Data : NA9
2016/01/18 05:35:40 Info > Completed data mirroring process for Dimension Data : NA9.0 new workloads.0 updated platform networks.4 updated workloads.0 removed workloads. = Total Execute Time: 00:00:10.5110000
2016/01/18 05:35:40 Info > Completed data mirroring process.0 new platforms, 1 updated platforms = total elapsed time: 00:00:10.7390000
2016/01/18 05:44:57 Info > Starting workload performance collection
2016/01/18 05:47:39 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 05:47:56 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 05:48:33 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 05:48:51 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 05:49:23 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 05:49:42 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 05:50:14 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 05:50:34 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 05:51:05 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 05:51:05 Info > Completed performance collection | Elapsed Time 00:06:07.9730000 
2016/01/18 06:21:05 Info > Starting workload performance collection
2016/01/18 06:23:51 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 06:23:58 Info > Staring data upload process
2016/01/18 06:24:09 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 06:24:42 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 06:24:58 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 06:25:20 Info > Completed data upload process.0 netflows.420 performancecounters. = Total Elapsed Time: 00:01:22.3590000
2016/01/18 06:25:36 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 06:25:52 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 06:26:23 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 06:26:40 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 06:27:15 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 06:27:15 Info > Completed performance collection | Elapsed Time 00:06:09.9430000 
2016/01/18 06:35:40 Info > Staring platform inventory process
2016/01/18 06:35:40 Info > Started data mirroring process for Dimension Data : NA9
2016/01/18 06:35:51 Info > Completed data mirroring process for Dimension Data : NA9.0 new workloads.0 updated platform networks.4 updated workloads.0 removed workloads. = Total Execute Time: 00:00:10.1700000
2016/01/18 06:35:51 Info > Completed data mirroring process.0 new platforms, 1 updated platforms = total elapsed time: 00:00:10.4120000
2016/01/18 06:57:15 Info > Starting workload performance collection
2016/01/18 07:00:01 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 07:00:18 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 07:00:51 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 07:01:07 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 07:01:38 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 07:01:57 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 07:02:27 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 07:02:41 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 07:02:59 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 07:03:20 Info > Completed performance collection | Elapsed Time 00:06:04.8700000 
2016/01/18 07:25:20 Info > Staring data upload process
2016/01/18 07:26:02 Info > Completed data upload process.0 netflows.210 performancecounters. = Total Elapsed Time: 00:00:41.4820000
2016/01/18 07:33:20 Info > Starting workload performance collection
2016/01/18 07:35:51 Info > Staring platform inventory process
2016/01/18 07:35:51 Info > Started data mirroring process for Dimension Data : NA9
2016/01/18 07:36:01 Info > Completed data mirroring process for Dimension Data : NA9.0 new workloads.0 updated platform networks.4 updated workloads.0 removed workloads. = Total Execute Time: 00:00:10.5070000
2016/01/18 07:36:01 Info > Completed data mirroring process.0 new platforms, 1 updated platforms = total elapsed time: 00:00:10.7290000
2016/01/18 07:36:07 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 07:36:26 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 07:37:01 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 07:37:19 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 07:37:52 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 07:38:09 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 07:38:44 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 07:39:02 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 07:39:35 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 07:39:35 Info > Completed performance collection | Elapsed Time 00:06:15.1440000 
2016/01/18 08:09:35 Info > Starting workload performance collection
2016/01/18 08:12:27 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 08:12:43 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 08:13:16 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 08:13:34 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 08:14:12 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 08:14:30 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 08:15:06 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 08:15:23 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 08:16:03 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 08:16:03 Info > Completed performance collection | Elapsed Time 00:06:27.6440000 
2016/01/18 08:26:02 Info > Staring data upload process
2016/01/18 08:27:35 Info > Completed data upload process.0 netflows.420 performancecounters. = Total Elapsed Time: 00:01:32.7380000
2016/01/18 08:36:01 Info > Staring platform inventory process
2016/01/18 08:36:02 Info > Started data mirroring process for Dimension Data : NA9
2016/01/18 08:36:11 Info > Completed data mirroring process for Dimension Data : NA9.0 new workloads.0 updated platform networks.4 updated workloads.0 removed workloads. = Total Execute Time: 00:00:09.2080000
2016/01/18 08:36:11 Info > Completed data mirroring process.0 new platforms, 1 updated platforms = total elapsed time: 00:00:09.4690000
2016/01/18 08:46:03 Info > Starting workload performance collection
2016/01/18 08:48:55 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 08:49:13 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 08:49:46 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 08:50:04 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 08:50:35 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 08:50:51 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 08:51:05 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 08:51:40 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 08:51:57 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 08:51:57 Info > Completed performance collection | Elapsed Time 00:05:54.7750000 
2016/01/18 09:21:57 Info > Starting workload performance collection
2016/01/18 09:25:15 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 09:25:26 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 09:25:45 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 09:26:17 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 09:26:36 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 09:27:12 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 09:27:29 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 09:27:35 Info > Staring data upload process
2016/01/18 09:28:02 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 09:28:18 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 09:28:18 Info > Completed performance collection | Elapsed Time 00:06:20.5850000 
2016/01/18 09:28:55 Info > Completed data upload process.0 netflows.420 performancecounters. = Total Elapsed Time: 00:01:20.3840000
2016/01/18 09:36:11 Info > Staring platform inventory process
2016/01/18 09:36:11 Info > Started data mirroring process for Dimension Data : NA9
2016/01/18 09:36:23 Info > Completed data mirroring process for Dimension Data : NA9.0 new workloads.0 updated platform networks.4 updated workloads.0 removed workloads. = Total Execute Time: 00:00:11.9870000
2016/01/18 09:36:23 Info > Completed data mirroring process.0 new platforms, 1 updated platforms = total elapsed time: 00:00:12.2020000
2016/01/18 09:58:18 Info > Starting workload performance collection
2016/01/18 10:01:44 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 10:02:01 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 10:02:35 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 10:02:50 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 10:03:25 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 10:03:41 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 10:04:15 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 10:04:30 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 10:05:06 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 10:05:06 Info > Completed performance collection | Elapsed Time 00:06:47.6500000 
2016/01/18 10:28:55 Info > Staring data upload process
2016/01/18 10:29:40 Info > Completed data upload process.0 netflows.210 performancecounters. = Total Elapsed Time: 00:00:44.9280000
2016/01/18 10:35:06 Info > Starting workload performance collection
2016/01/18 10:36:23 Info > Staring platform inventory process
2016/01/18 10:36:23 Info > Started data mirroring process for Dimension Data : NA9
2016/01/18 10:36:35 Info > Completed data mirroring process for Dimension Data : NA9.0 new workloads.0 updated platform networks.4 updated workloads.0 removed workloads. = Total Execute Time: 00:00:12.2030000
2016/01/18 10:36:35 Info > Completed data mirroring process.0 new platforms, 1 updated platforms = total elapsed time: 00:00:12.4110000
2016/01/18 10:37:55 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 10:38:15 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 10:38:50 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 10:39:07 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 10:39:42 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 10:39:57 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 10:40:34 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 10:40:48 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 10:41:18 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 10:41:19 Info > Completed performance collection | Elapsed Time 00:06:12.7900000 
2016/01/18 11:11:19 Info > Starting workload performance collection
2016/01/18 11:14:12 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 11:14:29 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 11:15:02 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 11:15:22 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 11:16:02 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 11:16:18 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 11:16:47 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 11:17:07 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 11:17:39 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 11:17:41 Info > Completed performance collection | Elapsed Time 00:06:22.8980000 
2016/01/18 11:29:40 Info > Staring data upload process
2016/01/18 11:30:22 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.)
2016/01/18 11:30:24 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.)
2016/01/18 11:31:27 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (Unable to connect to the remote server)
2016/01/18 11:31:41 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (Unable to connect to the remote server)
2016/01/18 11:32:18 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:32:43 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:33:19 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:33:48 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:34:10 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:34:39 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:35:01 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:35:41 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:35:49 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:36:32 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:36:35 Info > Staring platform inventory process
2016/01/18 11:36:38 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:37:01 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:37:20 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:37:20 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:38:04 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:38:11 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:38:16 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:38:55 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:39:02 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:39:08 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:39:46 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:39:50 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:39:58 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:40:37 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:40:43 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:40:50 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:41:28 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:41:32 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:41:40 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:42:25 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:42:32 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:42:44 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:43:28 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:43:34 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:43:48 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:44:16 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:44:16 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:44:39 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:44:58 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:45:04 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:45:30 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:45:49 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:45:55 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:46:43 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:46:52 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:46:58 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:47:34 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:47:40 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:47:42 Info > Starting workload performance collection
2016/01/18 11:47:46 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:48:04 Error > 2607:f480:111:1520:5c79:c1bf:3414:939c returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 11:48:04 Error > 2607:f480:111:1520:5c79:c1bf:3414:939c returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 11:48:04 Error > 2607:f480:111:1520:5c79:c1bf:3414:939c returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 11:48:04 Error > 2607:f480:111:1520:5c79:c1bf:3414:939c returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 11:48:04 Error > 2607:f480:111:1520:5c79:c1bf:3414:939c returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 11:48:05 Error > 2607:f480:111:1520:5c79:c1bf:3414:939c returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 11:48:05 Error > 2607:f480:111:1520:5c79:c1bf:3414:939c returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 11:48:05 Error > 2607:f480:111:1520:5c79:c1bf:3414:939c returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 11:48:05 Error > 2607:f480:111:1520:5c79:c1bf:3414:939c returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 11:48:22 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:48:31 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:48:38 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:48:53 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:49:14 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:49:14 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:49:26 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:49:44 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:49:56 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:50:02 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:50:08 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:50:35 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:50:44 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:50:47 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:50:56 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:51:41 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:51:47 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:51:53 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:51:59 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:52:42 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:52:48 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:53:03 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:53:09 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:53:30 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:53:30 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:53:58 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:54:04 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:54:21 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:54:28 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:54:40 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:55:09 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:55:10 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:55:21 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:55:22 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:56:00 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:56:04 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:56:12 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:56:16 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:56:57 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:56:58 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:57:09 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:57:10 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:57:49 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:57:52 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:58:01 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:58:17 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:58:34 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:58:37 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:58:46 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:59:07 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:59:19 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:59:23 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 11:59:31 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:00:18 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:00:21 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:00:30 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:00:33 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:01:06 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:01:09 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:01:18 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:01:21 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:01:54 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:01:57 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:02:06 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:02:09 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:02:46 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:02:58 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:02:58 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:03:49 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/tasks/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:03:50 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/workloads/update.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:04:04 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/performancecounters/create.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:04:04 Error > Unexpected error connecting to https://www.cloudmovey.com/api/v1/platforms/list.json with error (The remote name could not be resolved: 'www.cloudmovey.com')
2016/01/18 12:04:21 Error > System.Net.NetworkInformation.PingException: An exception occurred during a Ping request. ---> System.ComponentModel.Win32Exception: Unknown error (0x2b2a)
   at System.Net.NetworkInformation.Ping.InternalSend(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options, Boolean async)
   at System.Net.NetworkInformation.Ping.Send(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options)
   --- End of inner exception stack trace ---
   at System.Net.NetworkInformation.Ping.Send(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options)
   at System.Net.NetworkInformation.Ping.Send(String hostNameOrAddress, Int32 timeout, Byte[] buffer, PingOptions options)
   at System.Net.NetworkInformation.Ping.Send(String hostNameOrAddress, Int32 timeout)
   at CloudMoveyWorkerService.CloudMovey.Classes.Static_Classes.Connection.find_working_ip(Workload _workload, Boolean literal) in C:\Users\Phillip Spies\Documents\GitHubVisualStudio\CloudMoveyWorkerService\CloudMoveyWorkerService\CloudMoveyWorkerService\Classes\Connection.cs:line 52
   at CloudMoveyWorkerService.Portal.Classes.Static_Classes.Background_Classes.PerformanceWorker.Start() in C:\Users\Phillip Spies\Documents\GitHubVisualStudio\CloudMoveyWorkerService\CloudMoveyWorkerService\CloudMoveyWorkerService\Classes\Background Classes\PerformanceWorker.cs:line 124
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2016/01/18 10:41:10 Info > Starting CloudMovey Worker Service
2016/01/18 10:41:10 Info > Debug Enabled!
2016/01/18 10:41:10 Info > CloudMovey Worker Agent ID:636aafd21e70435fabe6374a099322d4
2016/01/18 10:41:11 Info > CloudMovey Portal URL:https://www.cloudmovey.com
2016/01/18 10:41:22 Debug > Starting WCF Service | Platforms: 1, Workloads: 5, Credentials: 2, Performance Counters: 320, Network Flows: 0
2016/01/18 10:41:27 Debug > organization id: 7b6865d87b824b4a97d563ae5e5d35e7
2016/01/18 10:41:27 Debug > Starting Scheduler Thread
2016/01/18 10:41:27 Debug > Starting Mirror Thread
2016/01/18 10:41:27 Debug > Starting Performance Collection Thread
2016/01/18 10:41:28 Info > Staring platform inventory process
2016/01/18 10:41:28 Debug > Starting Netflow v5 Collection Thread
2016/01/18 10:41:28 Debug > Starting Data Upload Thread
2016/01/18 10:41:28 Info > Starting workload performance collection
2016/01/18 10:41:28 Debug > Starting OS Inventory Thread
2016/01/18 10:41:28 Info > Staring data upload process
2016/01/18 10:41:29 Info > Staring operating system inventory process
2016/01/18 10:41:29 Info > Started data mirroring process for Dimension Data : NA9
2016/01/18 10:41:51 Info > Completed data mirroring process for Dimension Data : NA9.0 new workloads.0 updated platform networks.4 updated workloads.0 removed workloads. = Total Execute Time: 00:00:22.1120000
2016/01/18 10:41:51 Info > Completed data mirroring process.0 new platforms, 1 updated platforms = total elapsed time: 00:00:23.9300000
2016/01/18 10:42:21 Error > Error connecting to WMI : dbserver01 : 2607-f480-111-1520-1c67-edaa-40ac-5ad9.ipv6-literal.net [The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)]
2016/01/18 10:43:17 Info > Completed operating system inventory. [updated workloads.0] = Total Execute Time: 00:01:48.8040000
2016/01/18 10:44:12 Info > Completed data upload process.0 netflows.320 performancecounters. = Total Elapsed Time: 00:02:43.8240000
2016/01/18 10:46:56 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 10:47:11 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 10:47:46 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 10:48:02 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 10:48:37 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 10:48:52 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 10:49:25 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 10:49:44 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 10:50:14 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 10:50:14 Info > Completed performance collection | Elapsed Time 00:08:46.3870000 
2016/01/18 11:20:14 Info > Starting workload performance collection
2016/01/18 11:22:54 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 11:23:13 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 11:23:47 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 11:24:05 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

2016/01/18 11:24:36 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Network Interface : The network path was not found.

2016/01/18 11:24:53 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Connection : The network path was not found.

2016/01/18 11:25:23 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Kernel : The network path was not found.

2016/01/18 11:25:38 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Source : The network path was not found.

2016/01/18 11:26:16 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Double-Take Target : The network path was not found.

2016/01/18 11:26:16 Info > Completed performance collection | Elapsed Time 00:06:01.8560000 
2016/01/18 11:41:51 Info > Staring platform inventory process
2016/01/18 11:41:52 Info > Started data mirroring process for Dimension Data : NA9
2016/01/18 11:42:01 Info > Completed data mirroring process for Dimension Data : NA9.0 new workloads.0 updated platform networks.4 updated workloads.0 removed workloads. = Total Execute Time: 00:00:09.5470000
2016/01/18 11:42:01 Info > Completed data mirroring process.0 new platforms, 1 updated platforms = total elapsed time: 00:00:09.8140000
2016/01/18 11:44:12 Info > Staring data upload process
2016/01/18 11:45:31 Info > Completed data upload process.0 netflows.420 performancecounters. = Total Elapsed Time: 00:01:19.0510000
2016/01/18 11:56:16 Info > Starting workload performance collection
2016/01/18 11:58:32 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Processor : The network path was not found.

2016/01/18 11:58:53 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : Memory : The network path was not found.

2016/01/18 11:59:22 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : LogicalDisk : The network path was not found.

2016/01/18 11:59:37 Error > 2607:f480:111:1520:1c67:edaa:40ac:5ad9 returned the following error while collecting performance data for counter : PhysicalDisk : The network path was not found.

